version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
   install:
   - requirements: docs/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
