version: 2

python:
  version: "3.8"
  install:
    - methond: pip
      extra_requirements:
        - myst-parser

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
