site_name: DETO_3D
site_url: https://DETO.com/
repo_url: https://github.com/Connor-OS/DETO

markdown_extensions:
  - admonition

nav:
    - Home: index.md
    - 1. Instalation:
      - 1.1. Cloning: 1_instaling/1.1_cloning.md
      - 1.2. Submodules: 1_instaling/1.2_submodules.md
      - 1.3. Building: 1_instaling/1.3_building.md
    - 2. Input:
      - 2.1. Input: 2_running/2.1_input.md
      - 2.2. Chi Map: 2_running/2.2_chimap.md
      - 2.3. Potfile: 2_running/2.3_potfile.md
    - 3. commands:
      - 3.1. subcomm: 3_commands/3.1_subcomm.md
      - 3.2. lammps: 3_commands/3.2_lammps.md
      - 3.3. simulation: 3_commands/3.3_simulation.md
      - 3.4. add_attribute: 3_commands/3.4_add_attribute.md
      - 3.5. opt_map_chi: 3_commands/3.5_opt_map_chi.md
      - 3.6. read_potentials: 3_commands/3.6_read_potentials.md
      - 3.7. opt_type: 3_commands/3.7_opt_type.md
      - 3.8. objective_function: 3_commands/3.8_objective_function.md
      - 3.9. add_objective: 3_commands/3.9_add_objective.md
      - 3.10. add_constraint: 3_commands/3.10_add_constraint.md
      - 3.11. dump: 3_commands/3.11_dump.md
      - 3.12. write_plog: 3_commands/3.12_write_plog.md
      - 3.13. write_lmp_log: 3_commands/3.13_write_lmp_log.md
    - 4. examples:
      - 4.1. L Shaped beam: 4_examples/4.1_L_Shape.md

theme: readthedocs
